### ISSUE TITLE
Can't run AtEar-WIDS 

### ISSUE THREAD

**Issue by Emilien942702** [NORMA-Inc/AtEar#12]
Hi, i'm running AtEar last version on Kali Linux (latest version too, rolling), with everything up to date, and when i try to run the wireless scan from the web interface with my AWUS036NHA i'm not getting anything from the web interface, here is the log of the terminal :

```
[*] Start scanning network 
[*] START AtEar-WIDS
[2016-11-04 20:50:36,503] ERROR in app: Exception on /api/scanstatus [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "run.py", line 97, in scanstatus
    wids = Wireless_IDS(self.scan_iface)
  File "/root/Bureau/AtEar/module/wids.py", line 98, in __init__
    open(self.essidfile, "wb").write("")
IOError: [Errno 2] No such file or directory: '/root/Bureau/AtEar/module/../log/essidcount.log'
```
I also have a warning when i launch AtEar 

`WARNING: No route found for IPv6 destination :: (no default route?`

Do you have any fix for this issue ?
Thanks

**Comment by NORMA-Inc** [comment]
Did you check the log in AtEar Folder ?
If it doesn't exist in that directory, Please clone it again or make log folder.

**Comment by Emilien942702** [comment]
Hi,
The folder didn't exist.
Cloned it back, now the scan is working
But i'm getting an error while launching the Penetration option (while the interface os stuck at 3%)
Here is the error from the terminal :

**Comment by azamet90** [comment]
i have same problem log folder is exist but in the folder is empty
```
/home/azamet/Downloads/AtEar
[2018-11-06 23:08:55,408] ERROR in app: Exception on /api/scanstatus [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "run.py", line 100, in scanstatus
    wids = Wireless_IDS(self.scan_iface)
  File "/home/azamet/Downloads/AtEar/module/wids.py", line 90, in __init__
    signal.signal(signal.SIGTERM, signal_handler)
ValueError: signal only works in main thread

```



other error codes:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "run.py", line 100, in scanstatus
    wids = Wireless_IDS(self.scan_iface)
  File "/home/azamet/Downloads/AtEar/module/wids.py", line 90, in __init__
    signal.signal(signal.SIGTERM, signal_handler)
ValueError: signal only works in main thread
127.0.0.1 - - [06/Nov/2018 23:12:16] "GET /api/scanstatus HTTP/1.1" 500 -

```



im using kali linux latest version
